# -*- coding: utf-8 -*-
"""
/***************************************************************************
 rastrainer
                                 A QGIS plugin
 rastrainer is a QGIS plugin to training remote sensing semantic segmentation model based on PaddlePaddle.


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-11
        copyright            : (C) 2021 by deepbands
        email                : geoyee@yeah.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load rastrainer class from file rastrainer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rastrainer import rastrainer
    return rastrainer(iface)
